package amiga;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

import ghidra.framework.plugintool.ComponentProviderAdapter;
import ghidra.program.model.listing.Bookmark;
import ghidra.program.model.listing.BookmarkManager;
import ghidra.program.model.listing.Program;

/** Modeless table for reviewing candidates generated by AddressTakenCodeAnalyzer. */
class AddressTakenCodeReviewProvider extends ComponentProviderAdapter {

	private final AddressTakenCodeReviewPlugin plugin;
	private final DefaultTableModel model = new DefaultTableModel(new String[] { "Address", "Evidence" }, 0) {
		@Override
		public boolean isCellEditable(int row, int column) {
			return false;
		}
	};
	private final JTable table = new JTable(model);
	private final JLabel summary = new JLabel();
	private final List<Bookmark> candidates = new ArrayList<>();
	private final JPanel panel;
	private Program program;

	AddressTakenCodeReviewProvider(AddressTakenCodeReviewPlugin plugin) {
		super(plugin.getTool(), "Address-Taken Code Review", plugin.getName());
		this.plugin = plugin;
		table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		table.getSelectionModel().addListSelectionListener(event -> {
			if (!event.getValueIsAdjusting()) {
				Bookmark bookmark = selectedBookmark();
				if (bookmark != null) {
					plugin.goToCandidate(bookmark.getAddress());
				}
			}
		});
		panel = createPanel();
		tool.addComponentProvider(this, false);
	}

	@Override
	public JPanel getComponent() {
		return panel;
	}

	private JPanel createPanel() {
		JPanel panel = new JPanel(new BorderLayout(4, 4));
		JPanel actions = new JPanel();
		JButton promote = new JButton("Promote");
		promote.addActionListener(event -> promoteSelected());
		JButton dismiss = new JButton("Dismiss");
		dismiss.addActionListener(event -> dismissSelected());
		JButton refresh = new JButton("Refresh");
		refresh.addActionListener(event -> refresh());
		actions.add(promote);
		actions.add(dismiss);
		actions.add(refresh);
		panel.add(summary, BorderLayout.NORTH);
		panel.add(new JScrollPane(table), BorderLayout.CENTER);
		panel.add(actions, BorderLayout.SOUTH);
		panel.setPreferredSize(new Dimension(520, 260));
		return panel;
	}

	@Override
	public void componentShown() {
		refresh();
	}

	void setProgram(Program program) {
		this.program = program;
		if (isVisible()) {
			refresh();
		}
	}

	void showReview() {
		tool.showComponentProvider(this, true);
		refresh();
	}

	void dispose() {
		tool.removeComponentProvider(this);
	}

	private void refresh() {
		candidates.clear();
		model.setRowCount(0);
		if (program == null) {
			summary.setText("No program is open.");
			return;
		}
		BookmarkManager bookmarks = program.getBookmarkManager();
		Iterator<Bookmark> iterator = bookmarks.getBookmarksIterator(AddressTakenCodeAnalyzer.BOOKMARK_TYPE);
		while (iterator.hasNext()) {
			Bookmark bookmark = iterator.next();
			if (!AddressTakenCodeAnalyzer.BOOKMARK_CATEGORY.equals(bookmark.getCategory())) {
				continue;
			}
			candidates.add(bookmark);
			model.addRow(new Object[] { bookmark.getAddress(), bookmark.getComment() });
		}
		summary.setText(candidates.size() + " candidate" + (candidates.size() == 1 ? "" : "s") + " awaiting review.");
	}

	private Bookmark selectedBookmark() {
		int row = table.getSelectedRow();
		return row < 0 || row >= candidates.size() ? null : candidates.get(row);
	}

	private void promoteSelected() {
		Bookmark bookmark = selectedBookmark();
		if (bookmark != null && plugin.promote(bookmark)) {
			refresh();
		}
	}

	private void dismissSelected() {
		Bookmark bookmark = selectedBookmark();
		if (bookmark != null) {
			plugin.dismiss(bookmark);
			refresh();
		}
	}
}
