€ˆUTILITY_TAGITEM_H€UTILITY_TAGITEM_HˆEXEC_TYPES_HŒ<exec/types.h>‡
¥—Tag;
ƒTagItem
{
Tag ti_Tag;
—ti_Data;
};€TAG_DONE (0L)€TAG_END (0L)€TAG_IGNORE (1L)€TAG_MORE (2L)€TAG_SKIP (3L)€TAG_USER ((—)(1L<<31))€TAGFILTER_AND 0€TAGFILTER_NOT 1€MAP_REMOVE_NOT_FOUND 0€MAP_KEEP_NOT_FOUND 1‡