€ˆGRAPHICS_COPPER_H€GRAPHICS_COPPER_HˆEXEC_TYPES_HŒ<exec/types.h>‡€COPPER_MOVE 0€COPPER_WAIT 1€CPRNXTBUF 2€CPR_NT_LOF 0x8000€CPR_NT_SHT 0x4000€CPR_NT_SYS 0x2000
ƒCopIns
{
˜OpCode;
«
{
ƒCopList*nxtlist;
ƒ
{
«
{
˜VWaitPos;
˜DestAddr;
}u1;
«
{
˜HWaitPos;
˜DestData;
}u2;
}u4;
}u3;
};€NXTLIST u3.nxtlist€VWAITPOS u3.u4.u1.VWaitPos€DESTADDR u3.u4.u1.DestAddr€HWAITPOS u3.u4.u2.HWaitPos€DESTDATA u3.u4.u2.DestData
ƒcprlist
{
ƒcprlist*Next;
‰*start;
˜MaxCount;
};
ƒCopList
{
ƒCopList*Next;
ƒCopList*_CopList;
ƒViewPort*_ViewPort;
ƒCopIns*CopIns;
ƒCopIns*CopPtr;
‰*CopLStart;
‰*CopSStart;
˜Count;
˜MaxCount;
˜DyOffset;°V1_3
‰*Cop2Start;
‰*Cop3Start;
‰*Cop4Start;
‰*Cop5Start;‡
‰SLRepeat;
‰¦;
};€EXACT_LINE 1€HALF_LINE 2
ƒUCopList
{
ƒUCopList*Next;
ƒCopList*FirstCopList;
ƒCopList*CopList;
};
ƒcopinit
{
‰vsync_hblank[2];
‰diagstrt[12];
‰fm0[2];
‰diwstart[10];
‰bplcon2[2];
‰sprfix[2*8];
‰sprstrtup[(2*8*2)];
‰wait14[2];
‰norm_hblank[2];
‰jump[2];
‰wait_forever[6];
‰sprstop[8];
};‡