€ˆGRAPHICS_GFX_H€GRAPHICS_GFX_HˆEXEC_TYPES_HŒ<exec/types.h>‡€BITSET 0x8000€BITCLR 0€AGNUS°AGNUS€TOBB(a) (()(a))€TOBB(a) (()(a)>>1)‡
ƒRectangle
{
˜MinX,MinY;
˜MaxX,MaxY;
};
ƒRect32
{
’MinX,MinY;
’MaxX,MaxY;
};
¥ƒtPoint
{
˜x,y;
}Point;
¥Š*PLANEPTR;
ƒBitMap
{
‰BytesPerRow;
‰Rows;
Š¦;
ŠDepth;
‰pad;
PLANEPTR Planes[8];
};€RASSIZE(w,h) ((—)(h)*(((—)(w)+15)>>3&0xFFFE))€BMB_CLEAR 0€BMB_DISPLAYABLE 1€BMB_INTERLEAVED 2€BMB_STANDARD 3€BMB_MINPLANES 4€BMF_CLEAR (1l<<BMB_CLEAR)€BMF_DISPLAYABLE (1l<<BMB_DISPLAYABLE)€BMF_INTERLEAVED (1l<<BMB_INTERLEAVED)€BMF_STANDARD (1l<<BMB_STANDARD)€BMF_MINPLANES (1l<<BMB_MINPLANES)€BMA_HEIGHT 0€BMA_DEPTH 4€BMA_WIDTH 8€BMA_FLAGS 12‡