€ˆGRAPHICS_MONITOR_H€GRAPHICS_MONITOR_HˆEXEC_SEMAPHORES_HŒ<exec/semaphores.h>‡ˆGRAPHICS_GFXNODES_HŒ<graphics/gfxnodes.h>‡ˆGRAPHICS_GFX_HŒ<graphics/gfx.h>‡
ƒMonitorSpec
{
ƒExtendedNode ms_Node;
‰ms_Flags;
’ratioh;
’ratiov;
‰total_rows;
‰total_colorclocks;
‰DeniseMaxDisplayColumn;
‰BeamCon0;
‰min_row;
ƒSpecialMonitor*ms_Special;
‰ms_OpenCount;
’(*ms_transform)();
’(*ms_translate)();
’(*ms_scale)();
‰ms_xoffset;
‰ms_yoffset;
ƒRectangle ms_LegalView;
’(*ms_maxoscan)();
’(*ms_videoscan)();
‰DeniseMinDisplayColumn;
—DisplayCompatible;
ƒ®DisplayInfoDataBase;
ƒSignalSemaphore DisplayInfoDataBaseSemaphore;
’(*ms_MrgCop)();
’(*ms_LoadView)();
’(*ms_KillView)();
};€TO_MONITOR 0€FROM_MONITOR 1€STANDARD_XOFFSET 9€STANDARD_YOFFSET 0€MSB_REQUEST_NTSC 0€MSB_REQUEST_PAL 1€MSB_REQUEST_SPECIAL 2€MSB_REQUEST_A2024 3€MSB_DOUBLE_SPRITES 4€MSF_REQUEST_NTSC (1<<MSB_REQUEST_NTSC)€MSF_REQUEST_PAL (1<<MSB_REQUEST_PAL)€MSF_REQUEST_SPECIAL (1<<MSB_REQUEST_SPECIAL)€MSF_REQUEST_A2024 (1<<MSB_REQUEST_A2024)€MSF_DOUBLE_SPRITES (1<<MSB_DOUBLE_SPRITES)€REQUEST_NTSC (1<<MSB_REQUEST_NTSC)€REQUEST_PAL (1<<MSB_REQUEST_PAL)€REQUEST_SPECIAL (1<<MSB_REQUEST_SPECIAL)€REQUEST_A2024 (1<<MSB_REQUEST_A2024)€DEFAULT_MONITOR_NAME "default.monitor"€NTSC_MONITOR_NAME "ntsc.monitor"€PAL_MONITOR_NAME "pal.monitor"€STANDARD_MONITOR_MASK (REQUEST_NTSC|REQUEST_PAL)€STANDARD_NTSC_ROWS 262€STANDARD_PAL_ROWS 312€STANDARD_COLORCLOCKS 226€STANDARD_DENISE_MAX 455€STANDARD_DENISE_MIN 93€STANDARD_NTSC_BEAMCON (0)€STANDARD_PAL_BEAMCON (DISPLAYPAL)€SPECIAL_BEAMCON (VARVBLANK|LOLDIS|VARVSYNC|VARHSYNC|VARBEAM|CSBLANK|VSYNCTRUE)€MIN_NTSC_ROW 21€MIN_PAL_ROW 29€STANDARD_VIEW_X 129€STANDARD_VIEW_Y 44€STANDARD_HBSTRT 6€STANDARD_HSSTRT 11€STANDARD_HSSTOP 28€STANDARD_HBSTOP 44€STANDARD_VBSTRT 290€STANDARD_VSSTRT 678€STANDARD_VSSTOP 938€STANDARD_VBSTOP 0x1066€VGA_COLORCLOCKS (STANDARD_COLORCLOCKS/2)€VGA_TOTAL_ROWS (STANDARD_NTSC_ROWS*2)€VGA_DENISE_MIN 59€MIN_VGA_ROW 29€VGA_HBSTRT 8€VGA_HSSTRT 14€VGA_HSSTOP 28€VGA_HBSTOP 30€VGA_VBSTRT 0€VGA_VSSTRT 339€VGA_VSSTOP 565€VGA_VBSTOP 0xCCD€VGA_MONITOR_NAME "vga.monitor"€VGA70_COLORCLOCKS (STANDARD_COLORCLOCKS/2)€VGA70_TOTAL_ROWS 449€VGA70_DENISE_MIN 59€MIN_VGA70_ROW 35€VGA70_HBSTRT 8€VGA70_HSSTRT 14€VGA70_HSSTOP 28€VGA70_HBSTOP 30€VGA70_VBSTRT 0€VGA70_VSSTRT 678€VGA70_VSSTOP 904€VGA70_VBSTOP 0xF73€VGA70_BEAMCON (SPECIAL_BEAMCON^VSYNCTRUE)€VGA70_MONITOR_NAME "vga70.monitor"€BROADCAST_HBSTRT 1€BROADCAST_HSSTRT 6€BROADCAST_HSSTOP 23€BROADCAST_HBSTOP 39€BROADCAST_VBSTRT 0€BROADCAST_VSSTRT 678€BROADCAST_VSSTOP 0x54C€BROADCAST_VBSTOP 0x1C40€BROADCAST_BEAMCON (LOLDIS|CSBLANK)€RATIO_FIXEDPART 4€RATIO_UNITY (1<<RATIO_FIXEDPART)
ƒAnalogSignalInterval
{
‰asi_Start;
‰asi_Stop;
};
ƒSpecialMonitor
{
ƒExtendedNode spm_Node;
‰spm_Flags;
’(*do_monitor)();
’(*reserved1)();
’(*reserved2)();
’(*reserved3)();
ƒAnalogSignalInterval hblank;
ƒAnalogSignalInterval vblank;
ƒAnalogSignalInterval hsync;
ƒAnalogSignalInterval vsync;
};‡