€ˆGRAPHICS_VIEW_H€GRAPHICS_VIEW_H€ECS_SPECIFICˆEXEC_TYPES_HŒ<exec/types.h>‡ˆEXEC_SEMAPHORES_HŒ<exec/semaphores.h>‡ˆGRAPHICS_GFX_HŒ<graphics/gfx.h>‡ˆGRAPHICS_COPPER_HŒ<graphics/copper.h>‡ˆGRAPHICS_GFXNODES_HŒ<graphics/gfxnodes.h>‡ˆGRAPHICS_MONITOR_HŒ<graphics/monitor.h>‡ˆGRAPHICS_DISPLAYINFO_HŒ<graphics/displayinfo.h>‡ˆHARDWARE_CUSTOM_HŒ<hardware/custom.h>‡
ƒViewPort
{
ƒViewPort*Next;
ƒColorMap*ColorMap;
ƒCopList*DspIns;
ƒCopList*SprIns;
ƒCopList*ClrIns;
ƒUCopList*UCopIns;
˜DWidth,DHeight;
˜DxOffset,DyOffset;
‰Modes;
ŠSpritePriorities;
ŠExtendedModes;
ƒRasInfo*RasInfo;
};
ƒView
{
ƒViewPort*ViewPort;
ƒcprlist*LOFCprList;
ƒcprlist*SHFCprList;
˜DyOffset,DxOffset;
‰Modes;
};
ƒViewExtra
{
ƒExtendedNode n;
ƒView*View;
ƒMonitorSpec*Monitor;
‰TopLine;
};
ƒViewPortExtra
{
ƒExtendedNode n;
ƒViewPort*ViewPort;
ƒRectangle DisplayClip;
”VecTable;
”DriverData[2];
‰¦;
Point Origin[2];
—cop1ptr;
—cop2ptr;
};€VPXB_FREE_ME 0€VPXF_FREE_ME (1<<VPXB_FREE_ME)€VPXB_LAST 1€VPXF_LAST (1<<VPXB_LAST)€VPXB_STRADDLES_256 4€VPXF_STRADDLES_256 (1<<VPXB_STRADDLES_256)€VPXB_STRADDLES_512 5€VPXF_STRADDLES_512 (1<<VPXB_STRADDLES_512)€EXTEND_VSTRUCT 0x1000€VPF_A2024 64€VPF_TENHZ 32€VPB_A2024 6€VPB_TENHZ 4€GENLOCK_VIDEO 2€LACE 4€DOUBLESCAN 8€SUPERHIRES 32€PFBA 64€EXTRA_HALFBRITE 128€GENLOCK_AUDIO 256€DUALPF 0x400€HAM 0x800€EXTENDED_MODE 0x1000€VP_HIDE 0x2000€SPRITES 0x4000€HIRES 0x8000
ƒRasInfo
{
ƒRasInfo*Next;
ƒBitMap*BitMap;
˜RxOffset,RyOffset;
};
ƒColorMap
{
Š¦;
ŠType;
‰Count;
”ColorTable;
ƒViewPortExtra*cm_vpe;
”LowColorBits;
ŠTransparencyPlane;
ŠSpriteResolution;
ŠSpriteResDefault;
ŠAuxFlags;
ƒViewPort*cm_vp;
”NormalDisplayInfo;
”CoerceDisplayInfo;
ƒTagItem*cm_batch_items;
—VPModeID;
ƒPaletteExtra*PalExtra;
‰SpriteBase_Even;
‰SpriteBase_Odd;
‰Bp_0_base;
‰Bp_1_base;
};€COLORMAP_TYPE_V1_2 0€COLORMAP_TYPE_V1_4 1€COLORMAP_TYPE_V36 COLORMAP_TYPE_V1_4€COLORMAP_TYPE_V39 2€COLORMAP_TRANSPARENCY 1€COLORPLANE_TRANSPARENCY 2€BORDER_BLANKING 4€BORDER_NOTRANSPARENCY 8€VIDEOCONTROL_BATCH 16€USER_COPPER_CLIP 32€BORDERSPRITES 64€CMF_CMTRANS 0€CMF_CPTRANS 1€CMF_BRDRBLNK 2€CMF_BRDNTRAN 3€CMF_BRDRSPRT 6€SPRITERESN_ECS 0€SPRITERESN_140NS 1€SPRITERESN_70NS 2€SPRITERESN_35NS 3€SPRITERESN_DEFAULT -1€CMAB_FULLPALETTE 0€CMAF_FULLPALETTE (1<<CMAB_FULLPALETTE)€CMAB_NO_INTERMED_UPDATE 1€CMAF_NO_INTERMED_UPDATE (1<<CMAB_NO_INTERMED_UPDATE)€CMAB_NO_COLOR_LOAD 2€CMAF_NO_COLOR_LOAD (1<<CMAB_NO_COLOR_LOAD)€CMAB_DUALPF_DISABLE 3€CMAF_DUALPF_DISABLE (1<<CMAB_DUALPF_DISABLE)
ƒPaletteExtra
{
ƒSignalSemaphore pe_Semaphore;
‰pe_FirstFree;
‰pe_NFree;
‰pe_FirstShared;
‰pe_NShared;
Š*pe_RefCnt;
Š*pe_AllocList;
ƒViewPort*pe_ViewPort;
‰pe_SharableColors;
};€PENB_EXCLUSIVE 0€PENB_NO_SETCOLOR 1€PENF_EXCLUSIVE (1l<<PENB_EXCLUSIVE)€PENF_NO_SETCOLOR (1l<<PENB_NO_SETCOLOR)€PEN_EXCLUSIVE PENF_EXCLUSIVE€PEN_NO_SETCOLOR PENF_NO_SETCOLOR€PRECISION_EXACT -1€PRECISION_IMAGE 0€PRECISION_ICON 16€PRECISION_GUI 32€OBP_Precision 0x84000000€OBP_FailIfBad 0x84000001€MVP_OK 0€MVP_NO_MEM 1€MVP_NO_VPE 2€MVP_NO_DSPINS 3€MVP_NO_DISPLAY 4€MVP_OFF_BOTTOM 5€MCOP_OK 0€MCOP_NO_MEM 1€MCOP_NOP 2
ƒDBufInfo{
”dbi_Link1;
—dbi_Count1;
ƒ¯dbi_SafeMessage;
”dbi_UserData1;
”dbi_Link2;
—dbi_Count2;
ƒ¯dbi_DispMessage;
”dbi_UserData2;
—dbi_MatchLong;
”dbi_CopPtr1;
”dbi_CopPtr2;
”dbi_CopPtr3;
‰dbi_BeamPos1;
‰dbi_BeamPos2;
};‡