€ˆCLIB_EXEC_PROTOS_H€CLIB_EXEC_PROTOS_HˆEXEC_TYPES_HŒ<exec/types.h>‡ˆEXEC_TASKS_HŒ<exec/tasks.h>‡
—Supervisor((*userFunction)());
‹InitCode(startClass,version);
‹InitStruct(”initTable,”memory,size);
ƒLibrary*MakeLibrary(”funcInit,”structInit,
(*libInit)(),dataSize,
segList);
‹MakeFunctions(”target,”functionArray,
funcDispBase);
ƒResident*FindResident(Š*name);
”InitResident(ƒResident*resident,segList);
‹Alert(alertNum);
‹Debug(flags);
‹Disable(‹);
‹Enable(‹);
‹Forbid(‹);
‹Permit(‹);
—SetSR(newSR,mask);
”SuperState(‹);
‹UserState(”sysStack);
ƒInterrupt*SetIntVector(intNumber,ƒInterrupt*interrupt);
‹AddIntServer(intNumber,ƒInterrupt*interrupt);
‹RemIntServer(intNumber,ƒInterrupt*interrupt);
‹Cause(ƒInterrupt*interrupt);
”Allocate(ƒMemHeader*freeList,byteSize);
‹Deallocate(ƒMemHeader*freeList,”memoryBlock,
byteSize);
”AllocMem(byteSize,requirements);
”AllocAbs(byteSize,”location);
‹FreeMem(”memoryBlock,byteSize);
—AvailMem(requirements);
ƒMemList*AllocEntry(ƒMemList*entry);
‹FreeEntry(ƒMemList*entry);
‹Insert(ƒ®*list,ƒ¬*node,ƒ¬*pred);
‹AddHead(ƒ®*list,ƒ¬*node);
‹AddTail(ƒ®*list,ƒ¬*node);
‹Remove(ƒ¬*node);
ƒ¬*RemHead(ƒ®*list);
ƒ¬*RemTail(ƒ®*list);
‹Enqueue(ƒ®*list,ƒ¬*node);
ƒ¬*FindName(ƒ®*list,Š*name);
”AddTask(ƒTask*task,”initPC,”finalPC);
‹RemTask(ƒTask*task);
ƒTask*FindTask(Š*name);
šSetTaskPri(ƒTask*task,priority);
—SetSignal(newSignals,signalSet);
—SetExcept(newSignals,signalSet);
—Wait(signalSet);
‹Signal(ƒTask*task,signalSet);
šAllocSignal(signalNum);
‹FreeSignal(signalNum);
’AllocTrap(trapNum);
‹FreeTrap(trapNum);
‹AddPort(ƒ©*port);
‹RemPort(ƒ©*port);
‹PutMsg(ƒ©*port,ƒ¯*message);
ƒ¯*GetMsg(ƒ©*port);
‹ReplyMsg(ƒ¯*message);
ƒ¯*WaitPort(ƒ©*port);
ƒ©*FindPort(Š*name);
‹AddLibrary(ƒLibrary*library);
‹RemLibrary(ƒLibrary*library);
ƒLibrary*OldOpenLibrary(Š*libName);
‹CloseLibrary(ƒLibrary*library);
”SetFunction(ƒLibrary*library,funcOffset,
(*newFunction)());
‹SumLibrary(ƒLibrary*library);
‹AddDevice(ƒDevice*device);
‹RemDevice(ƒDevice*device);
šOpenDevice(Š*devName,unit,
ƒIORequest*ioRequest,flags);
‹CloseDevice(ƒIORequest*ioRequest);
šDoIO(ƒIORequest*ioRequest);
‹SendIO(ƒIORequest*ioRequest);
BOOL CheckIO(ƒIORequest*ioRequest);
šWaitIO(ƒIORequest*ioRequest);
‹AbortIO(ƒIORequest*ioRequest);
‹AddResource(”resource);
‹RemResource(”resource);
”OpenResource(Š*resName);
”RawDoFmt(Š*formatString,”dataStream,‹(*putChProc)(),
”putChData);
—GetCC(‹);
—TypeOfMem(”address);
—Procure(ƒSignalSemaphore*sigSem,
ƒSemaphoreMessage*bidMsg);
‹Vacate(ƒSignalSemaphore*sigSem,
ƒSemaphoreMessage*bidMsg);
ƒLibrary*OpenLibrary(Š*libName,version);
‹InitSemaphore(ƒSignalSemaphore*sigSem);
‹ObtainSemaphore(ƒSignalSemaphore*sigSem);
‹ReleaseSemaphore(ƒSignalSemaphore*sigSem);
—AttemptSemaphore(ƒSignalSemaphore*sigSem);
‹ObtainSemaphoreList(ƒ®*sigSem);
‹ReleaseSemaphoreList(ƒ®*sigSem);
ƒSignalSemaphore*FindSemaphore(Š*sigSem);
‹AddSemaphore(ƒSignalSemaphore*sigSem);
‹RemSemaphore(ƒSignalSemaphore*sigSem);
—SumKickData(‹);
‹AddMemList(size,attributes,pri,
”base,Š*name);
‹CopyMem(”source,”dest,size);
‹CopyMemQuick(”source,”dest,size);
‹CacheClearU(‹);
‹CacheClearE(”address,length,caches);
—CacheControl(cacheBits,cacheMask);
”CreateIORequest(ƒ©*port,size);
‹DeleteIORequest(”iorequest);
ƒ©*CreateMsgPort(‹);
‹DeleteMsgPort(ƒ©*port);
‹ObtainSemaphoreShared(ƒSignalSemaphore*sigSem);
”AllocVec(byteSize,requirements);
‹FreeVec(”memoryBlock);
”CreatePool(requirements,puddleSize,
threshSize);
‹DeletePool(”poolHeader);
”AllocPooled(”poolHeader,memSize);
‹FreePooled(”poolHeader,”memory,memSize);
—AttemptSemaphoreShared(ƒSignalSemaphore*sigSem);
‹ColdReboot(‹);
‹StackSwap(ƒStackSwapStruct*newStack);
‹ChildFree(”tid);
‹ChildOrphan(”tid);
‹ChildStatus(”tid);
‹ChildWait(”tid);
”CachePreDMA(”address,—*length,flags);
‹CachePostDMA(”address,—*length,flags);
‹AddMemHandler(ƒInterrupt*memhand);
‹RemMemHandler(ƒInterrupt*memhand);
—ObtainQuickVector(”interruptCode);‡