ÄàCLIB_IFFPARSE_PROTOS_HÄCLIB_IFFPARSE_PROTOS_HàEXEC_TYPES_Hå<exec/types.h>áàLIBRARIES_IFFPARSE_Hå<libraries/iffparse.h>á
ÉIFFHandle*AllocIFF(ã);
íOpenIFF(ÉIFFHandle*iff,çrwMode);
íParseIFF(ÉIFFHandle*iff,çcontrol);
ãCloseIFF(ÉIFFHandle*iff);
ãFreeIFF(ÉIFFHandle*iff);
íReadChunkBytes(ÉIFFHandle*iff,îbuf,çnumBytes);
íWriteChunkBytes(ÉIFFHandle*iff,îbuf,çnumBytes);
íReadChunkRecords(ÉIFFHandle*iff,îbuf,çbytesPerRecord,
çnumRecords);
íWriteChunkRecords(ÉIFFHandle*iff,îbuf,çbytesPerRecord,
çnumRecords);
íPushChunk(ÉIFFHandle*iff,çtype,çid,çsize);
íPopChunk(ÉIFFHandle*iff);
íEntryHandler(ÉIFFHandle*iff,çtype,çid,çposition,
ÉHook*handler,îobject);
íExitHandler(ÉIFFHandle*iff,çtype,çid,çposition,
ÉHook*handler,îobject);
íPropChunk(ÉIFFHandle*iff,çtype,çid);
íPropChunks(ÉIFFHandle*iff,í*propArray,çnumPairs);
íStopChunk(ÉIFFHandle*iff,çtype,çid);
íStopChunks(ÉIFFHandle*iff,í*propArray,çnumPairs);
íCollectionChunk(ÉIFFHandle*iff,çtype,çid);
íCollectionChunks(ÉIFFHandle*iff,í*propArray,
çnumPairs);
íStopOnExit(ÉIFFHandle*iff,çtype,çid);
ÉStoredProperty*FindProp(ÉIFFHandle*iff,çtype,çid);
ÉCollectionItem*FindCollection(ÉIFFHandle*iff,çtype,
çid);
ÉContextNode*FindPropContext(ÉIFFHandle*iff);
ÉContextNode*CurrentChunk(ÉIFFHandle*iff);
ÉContextNode*ParentChunk(ÉContextNode*contextNode);
ÉLocalContextItem*AllocLocalItem(çtype,çid,çident,
çdataSize);
îLocalItemData(ÉLocalContextItem*localItem);
ãSetLocalItemPurge(ÉLocalContextItem*localItem,
ÉHook*purgeHook);
ãFreeLocalItem(ÉLocalContextItem*localItem);
ÉLocalContextItem*FindLocalItem(ÉIFFHandle*iff,çtype,
çid,çident);
íStoreLocalItem(ÉIFFHandle*iff,ÉLocalContextItem*localItem,
çposition);
ãStoreItemInContext(ÉIFFHandle*iff,
ÉLocalContextItem*localItem,
ÉContextNode*contextNode);
ãInitIFF(ÉIFFHandle*iff,çflags,ÉHook*streamHook);
ãInitIFFasDOS(ÉIFFHandle*iff);
ãInitIFFasClip(ÉIFFHandle*iff);
ÉClipboardHandle*OpenClipboard(çunitNumber);
ãCloseClipboard(ÉClipboardHandle*clipHandle);
íGoodID(çid);
íGoodType(çtype);
STRPTR IDtoStr(çid,STRPTR buf);á