€ˆCLIB_LAYERS_PROTOS_H€CLIB_LAYERS_PROTOS_HˆEXEC_TYPES_HŒ<exec/types.h>‡ˆGRAPHICS_LAYERS_HŒ<graphics/layers.h>‡ˆGRAPHICS_CLIP_HŒ<graphics/clip.h>‡ˆGRAPHICS_RASTPORT_HŒ<graphics/rastport.h>‡ˆGRAPHICS_REGIONS_HŒ<graphics/regions.h>‡
‹InitLayers(ƒLayer_Info*li);
ƒLayer*CreateUpfrontLayer(ƒLayer_Info*li,ƒBitMap*bm,
x0,y0,x1,y1,flags,ƒBitMap*bm2);
ƒLayer*CreateBehindLayer(ƒLayer_Info*li,ƒBitMap*bm,
x0,y0,x1,y1,flags,ƒBitMap*bm2);
’UpfrontLayer(dummy,ƒLayer*layer);
’BehindLayer(dummy,ƒLayer*layer);
’MoveLayer(dummy,ƒLayer*layer,dx,dy);
’SizeLayer(dummy,ƒLayer*layer,dx,dy);
‹ScrollLayer(dummy,ƒLayer*layer,dx,dy);
’BeginUpdate(ƒLayer*l);
‹EndUpdate(ƒLayer*layer,flag);
’DeleteLayer(dummy,ƒLayer*layer);
‹LockLayer(dummy,ƒLayer*layer);
‹UnlockLayer(ƒLayer*layer);
‹LockLayers(ƒLayer_Info*li);
‹UnlockLayers(ƒLayer_Info*li);
‹LockLayerInfo(ƒLayer_Info*li);
‹SwapBitsRastPortClipRect(ƒRastPort*rp,ƒClipRect*cr);
ƒLayer*WhichLayer(ƒLayer_Info*li,x,y);
‹UnlockLayerInfo(ƒLayer_Info*li);
ƒLayer_Info*NewLayerInfo(‹);
‹DisposeLayerInfo(ƒLayer_Info*li);
’FattenLayerInfo(ƒLayer_Info*li);
‹ThinLayerInfo(ƒLayer_Info*li);
’MoveLayerInFrontOf(ƒLayer*layer_to_move,
ƒLayer*other_layer);
ƒRegion*InstallClipRegion(ƒLayer*layer,
ƒRegion*region);
’MoveSizeLayer(ƒLayer*layer,dx,dy,dw,dh);
ƒLayer*CreateUpfrontHookLayer(ƒLayer_Info*li,ƒBitMap*bm,
x0,y0,x1,y1,flags,ƒHook*hook,
ƒBitMap*bm2);
ƒLayer*CreateBehindHookLayer(ƒLayer_Info*li,ƒBitMap*bm,
x0,y0,x1,y1,flags,ƒHook*hook,
ƒBitMap*bm2);
ƒHook*InstallLayerHook(ƒLayer*layer,ƒHook*hook);
ƒHook*InstallLayerInfoHook(ƒLayer_Info*li,ƒHook*hook);
‹SortLayerCR(ƒLayer*layer,dx,dy);
‹DoHookClipRects(ƒHook*hook,ƒRastPort*rport,
ƒRectangle*rect);‡