ÄàCLIB_MATHIEEEDOUBBAS_PROTOS_HÄCLIB_MATHIEEEDOUBBAS_PROTOS_HàEXEC_TYPES_Hå<exec/types.h>á
íIEEEDPFix(DOUBLE parm);
DOUBLE IEEEDPFlt(çinteger);
íIEEEDPCmp(DOUBLE leftParm,DOUBLE rightParm);
íIEEEDPTst(DOUBLE parm);
DOUBLE IEEEDPAbs(DOUBLE parm);
DOUBLE IEEEDPNeg(DOUBLE parm);
DOUBLE IEEEDPAdd(DOUBLE leftParm,DOUBLE rightParm);
DOUBLE IEEEDPSub(DOUBLE leftParm,DOUBLE rightParm);
DOUBLE IEEEDPMul(DOUBLE factor1,DOUBLE factor2);
DOUBLE IEEEDPDiv(DOUBLE dividend,DOUBLE divisor);
DOUBLE IEEEDPFloor(DOUBLE parm);
DOUBLE IEEEDPCeil(DOUBLE parm);á