€ˆCLIB_MATHIEEESINGTRANS_PROTOS_H€CLIB_MATHIEEESINGTRANS_PROTOS_HˆEXEC_TYPES_HŒ<exec/types.h>‡
¤IEEESPAtan(¤parm);
¤IEEESPSin(¤parm);
¤IEEESPCos(¤parm);
¤IEEESPTan(¤parm);
¤IEEESPSincos(¤*cosptr,¤parm);
¤IEEESPSinh(¤parm);
¤IEEESPCosh(¤parm);
¤IEEESPTanh(¤parm);
¤IEEESPExp(¤parm);
¤IEEESPLog(¤parm);
¤IEEESPPow(¤exp,¤arg);
¤IEEESPSqrt(¤parm);
¤IEEESPTieee(¤parm);
¤IEEESPFieee(¤parm);
¤IEEESPAsin(¤parm);
¤IEEESPAcos(¤parm);
¤IEEESPLog10(¤parm);‡