€ˆCLIB_MATHIEEEDOUBTRANS_PROTOS_H€CLIB_MATHIEEEDOUBTRANS_PROTOS_HˆEXEC_TYPES_HŒ<exec/types.h>‡
DOUBLE IEEEDPAtan(DOUBLE parm);
DOUBLE IEEEDPSin(DOUBLE parm);
DOUBLE IEEEDPCos(DOUBLE parm);
DOUBLE IEEEDPTan(DOUBLE parm);
DOUBLE IEEEDPSincos(DOUBLE*pf2,DOUBLE parm);
DOUBLE IEEEDPSinh(DOUBLE parm);
DOUBLE IEEEDPCosh(DOUBLE parm);
DOUBLE IEEEDPTanh(DOUBLE parm);
DOUBLE IEEEDPExp(DOUBLE parm);
DOUBLE IEEEDPLog(DOUBLE parm);
DOUBLE IEEEDPPow(DOUBLE exp,DOUBLE arg);
DOUBLE IEEEDPSqrt(DOUBLE parm);
¤IEEEDPTieee(DOUBLE parm);
DOUBLE IEEEDPFieee(¤single);
DOUBLE IEEEDPAsin(DOUBLE parm);
DOUBLE IEEEDPAcos(DOUBLE parm);
DOUBLE IEEEDPLog10(DOUBLE parm);‡