€ˆCLIB_MATHTRANS_PROTOS_H€CLIB_MATHTRANS_PROTOS_HˆEXEC_TYPES_HŒ<exec/types.h>‡
¤SPAtan(¤parm);
¤SPSin(¤parm);
¤SPCos(¤parm);
¤SPTan(¤parm);
¤SPSincos(¤*cosResult,¤parm);
¤SPSinh(¤parm);
¤SPCosh(¤parm);
¤SPTanh(¤parm);
¤SPExp(¤parm);
¤SPLog(¤parm);
¤SPPow(¤power,¤arg);
¤SPSqrt(¤parm);
¤SPTieee(¤parm);
¤SPFieee(¤parm);
¤SPAsin(¤parm);
¤SPAcos(¤parm);
¤SPLog10(¤parm);‡