€ˆINTUITION_IMAGECLASS_H€INTUITION_IMAGECLASS_H TRUEˆUTILITY_TAGITEM_HŒ<utility/tagitem.h>‡€CUSTOMIMAGEDEPTH (-1)€GADGET_BOX(g) ((ƒIBox*)&((ƒ»*)(g))->LeftEdge)€IM_BOX(im) ((ƒIBox*)&((ƒImage*)(im))->LeftEdge)€IM_FGPEN(im) ((im)->PlanePick)€IM_BGPEN(im) ((im)->PlaneOnOff)€IA_Dummy (TAG_USER+0x20000)€IA_Left (IA_Dummy+1)€IA_Top (IA_Dummy+2)€IA_Width (IA_Dummy+3)€IA_Height (IA_Dummy+4)€IA_FGPen (IA_Dummy+5)€IA_BGPen (IA_Dummy+6)€IA_Data (IA_Dummy+7)€IA_LineWidth (IA_Dummy+8)€IA_Pens (IA_Dummy+14)€IA_Resolution (IA_Dummy+15)€IA_APattern (IA_Dummy+16)€IA_APatSize (IA_Dummy+17)€IA_Mode (IA_Dummy+18)€IA_Font (IA_Dummy+19)€IA_Outline (IA_Dummy+20)€IA_Recessed (IA_Dummy+21)€IA_DoubleEmboss (IA_Dummy+22)€IA_EdgesOnly (IA_Dummy+23)€SYSIA_Size (IA_Dummy+11)€SYSIA_Depth (IA_Dummy+12)€SYSIA_Which (IA_Dummy+13)€SYSIA_DrawInfo (IA_Dummy+24)€SYSIA_Pens IA_Pens€IA_ShadowPen (IA_Dummy+9)€IA_HighlightPen (IA_Dummy+10)€SYSIA_ReferenceFont (IA_Dummy+25)€IA_SupportsDisable (IA_Dummy+26)€IA_FrameType (IA_Dummy+27)€SYSISIZE_MEDRES (0)€SYSISIZE_LOWRES (1)€SYSISIZE_HIRES (2)€DEPTHIMAGE (0x00L)€ZOOMIMAGE (0x01L)€SIZEIMAGE (0x02L)€CLOSEIMAGE (0x03L)€SDEPTHIMAGE (0x05L)€LEFTIMAGE (0x0AL)€UPIMAGE (0x0BL)€RIGHTIMAGE (0x0CL)€DOWNIMAGE (0x0DL)€CHECKIMAGE (0x0EL)€MXIMAGE (0x0FL)€MENUCHECK (0x10L)€AMIGAKEY (0x11L)€FRAME_DEFAULT 0€FRAME_BUTTON 1€FRAME_RIDGE 2€FRAME_ICONDROPBOX 3€IM_DRAW 514L€IM_HITTEST 515L€IM_ERASE 516L€IM_MOVE 517L€IM_DRAWFRAME 518L€IM_FRAMEBOX 519L€IM_HITFRAME 520L€IM_ERASEFRAME 521L€IDS_NORMAL (0L)€IDS_SELECTED (1L)€IDS_DISABLED (2L)€IDS_BUSY (3L)€IDS_INDETERMINATE (4L)€IDS_INACTIVENORMAL (5L)€IDS_INACTIVESELECTED (6L)€IDS_INACTIVEDISABLED (7L)€IDS_SELECTEDDISABLED (8L)€IDS_INDETERMINANT IDS_INDETERMINATE
ƒimpFrameBox{
—MethodID;
ƒIBox*imp_ContentsBox;
ƒIBox*imp_FrameBox;
ƒDrawInfo*imp_DrInfo;
—imp_FrameFlags;
};€FRAMEF_SPECIFY (1<<0)
ƒimpDraw{
—MethodID;
ƒRastPort*imp_RPort;
ƒ{
˜X;
˜Y;
}imp_Offset;
—imp_State;
ƒDrawInfo*imp_DrInfo;
ƒ{
˜Width;
˜Height;
}imp_Dimensions;
};
ƒimpErase{
—MethodID;
ƒRastPort*imp_RPort;
ƒ{
˜X;
˜Y;
}imp_Offset;
ƒ{
˜Width;
˜Height;
}imp_Dimensions;
};
ƒimpHitTest{
—MethodID;
ƒ{
˜X;
˜Y;
}imp_Point;
ƒ{
˜Width;
˜Height;
}imp_Dimensions;
};ˆINTUITION_IOBSOLETE_HŒ<intuition/iobsolete.h>‡‡