€ˆINTUITION_INTUITIONBASE_H€INTUITION_INTUITIONBASE_H 1ˆEXEC_TYPES_HŒ<exec/types.h>‡ˆEXEC_LIBRARIES_HŒ<exec/libraries.h>‡ˆINTUITION_INTUITION_HŒ<intuition/intuition.h>‡ˆEXEC_INTERRUPTS_HŒ<exec/interrupts.h>‡€DMODECOUNT 2€HIRESPICK 0€LOWRESPICK 1€EVENTMAX 10€RESCOUNT 2€HIRESGADGET 0€LOWRESGADGET 1€GADGETCOUNT 8€UPFRONTGADGET 0€DOWNBACKGADGET 1€SIZEGADGET 2€CLOSEGADGET 3€DRAGGADGET 4€SUPFRONTGADGET 5€SDOWNBACKGADGET 6€SDRAGGADGET 7
ƒ–
{
ƒLibrary LibNode;
ƒView ViewLord;
ƒWindow*ActiveWindow;
ƒScreen*ActiveScreen;
ƒScreen*FirstScreen;
—¦;
˜MouseY,MouseX;
—Seconds;
—Micros;
};‡