€ˆINTUITION_INTUITION_H€INTUITION_INTUITION_H TRUEˆEXEC_TYPES_HŒ<exec/types.h>‡ˆGRAPHICS_GFX_HŒ<graphics/gfx.h>‡ˆGRAPHICS_CLIP_HŒ<graphics/clip.h>‡ˆGRAPHICS_VIEW_HŒ<graphics/view.h>‡ˆGRAPHICS_RASTPORT_HŒ<graphics/rastport.h>‡ˆGRAPHICS_LAYERS_HŒ<graphics/layers.h>‡ˆGRAPHICS_TEXT_HŒ<graphics/text.h>‡ˆ¸Œ<exec/ports.h>‡ˆDEVICES_INPUTEVENT_HŒ<devices/inputevent.h>‡ˆUTILITY_TAGITEM_HŒ<utility/tagitem.h>‡
ƒMenu
{
ƒMenu*NextMenu;
˜LeftEdge,TopEdge;
˜Width,Height;
‰¦;
š*MenuName;
ƒMenuItem*FirstItem;
˜JazzX,JazzY,BeatX,BeatY;
};€MENUENABLED 1€MIDRAWN 256
ƒMenuItem
{
ƒMenuItem*NextItem;
˜LeftEdge,TopEdge;
˜Width,Height;
‰¦;
’MutualExclude;
”ItemFill;
”SelectFill;
šCommand;
ƒMenuItem*SubItem;
‰NextSelect;
};€CHECKIT 1€ITEMTEXT 2€COMMSEQ 4€MENUTOGGLE 8€ITEMENABLED 16€HIGHFLAGS 192€HIGHIMAGE 0€HIGHCOMP 64€HIGHBOX 128€HIGHNONE 192€CHECKED 256€ISDRAWN 0x1000€HIGHITEM 0x2000€MENUTOGGLED 0x4000
ƒRequester
{
ƒRequester*OlderRequest;
˜LeftEdge,TopEdge;
˜Width,Height;
˜RelLeft,RelTop;
ƒ»*ReqGadget;
ƒBorder*ReqBorder;
ƒIntuiText*ReqText;
‰¦;
ŠBackFill;
ƒLayer*ReqLayer;
ŠReqPad1[32];
ƒBitMap*ImageBMap;
ƒWindow*RWindow;
ƒImage*ReqImage;
ŠReqPad2[32];
};€POINTREL 1€PREDRAWN 2€NOISYREQ 4€SIMPLEREQ 16€USEREQIMAGE 32€NOREQBACKFILL 64€REQOFFWINDOW 0x1000€REQACTIVE 0x2000€SYSREQUEST 0x4000€DEFERREFRESH 0x8000
ƒ»
{
ƒ»*NextGadget;
˜LeftEdge,TopEdge;
˜Width,Height;
‰¦;
‰Activation;
‰GadgetType;
”GadgetRender;
”SelectRender;
ƒIntuiText*GadgetText;
’MutualExclude;
”SpecialInfo;
‰GadgetID;
”UserData;
};
ƒExtGadget
{
ƒExtGadget*NextGadget;
˜LeftEdge,TopEdge;
˜Width,Height;
‰¦;
‰Activation;
‰GadgetType;
”GadgetRender;
”SelectRender;
ƒIntuiText*GadgetText;
’MutualExclude;
”SpecialInfo;
‰GadgetID;
”UserData;
—MoreFlags;
˜BoundsLeftEdge;
˜BoundsTopEdge;
˜BoundsWidth;
˜BoundsHeight;
};€GFLG_GADGHIGHBITS 3€GFLG_GADGHCOMP 0€GFLG_GADGHBOX 1€GFLG_GADGHIMAGE 2€GFLG_GADGHNONE 3€GFLG_GADGIMAGE 4€GFLG_RELBOTTOM 8€GFLG_RELRIGHT 16€GFLG_RELWIDTH 32€GFLG_RELHEIGHT 64€GFLG_RELSPECIAL 0x4000€GFLG_SELECTED 128€GFLG_DISABLED 256€GFLG_LABELMASK 0x3000€GFLG_LABELITEXT 0€GFLG_LABELSTRING 0x1000€GFLG_LABELIMAGE 0x2000€GFLG_TABCYCLE 512€GFLG_STRINGEXTEND 0x400€GFLG_IMAGEDISABLE 0x800€GFLG_EXTENDED 0x8000€GACT_RELVERIFY 1€GACT_IMMEDIATE 2€GACT_ENDGADGET 4€GACT_FOLLOWMOUSE 8€GACT_RIGHTBORDER 16€GACT_LEFTBORDER 32€GACT_TOPBORDER 64€GACT_BOTTOMBORDER 128€GACT_BORDERSNIFF 0x8000€GACT_TOGGLESELECT 256€GACT_BOOLEXTEND 0x2000€GACT_STRINGLEFT 0€GACT_STRINGCENTER 512€GACT_STRINGRIGHT 0x400€GACT_LONGINT 0x800€GACT_ALTKEYMAP 0x1000€GACT_STRINGEXTEND 0x2000€GACT_ACTIVEGADGET 0x4000€GTYP_GADGETTYPE 0xFC00€GTYP_SCRGADGET 0x4000€GTYP_GZZGADGET 0x2000€GTYP_REQGADGET 0x1000€GTYP_SYSGADGET 0x8000€GTYP_SYSTYPEMASK 240€GTYP_SIZING 16€GTYP_WDRAGGING 32€GTYP_SDRAGGING 48€GTYP_WDEPTH 64€GTYP_SDEPTH 80€GTYP_WZOOM 96€GTYP_SUNUSED 112€GTYP_CLOSE 128€GTYP_WUPFRONT GTYP_WDEPTH€GTYP_SUPFRONT GTYP_SDEPTH€GTYP_WDOWNBACK GTYP_WZOOM€GTYP_SDOWNBACK GTYP_SUNUSED€GTYP_GTYPEMASK 7€GTYP_BOOLGADGET 1€GTYP_GADGET0002 2€GTYP_PROPGADGET 3€GTYP_STRGADGET 4€GTYP_CUSTOMGADGET 5€GMORE_BOUNDS 1€GMORE_GADGETHELP 2€GMORE_SCROLLRASTER 4
ƒBoolInfo
{
‰¦;
‰*Mask;
—Reserved;
};€BOOLMASK 1
ƒPropInfo
{
‰¦;
‰HorizPot;
‰VertPot;
‰HorizBody;
‰VertBody;
‰CWidth;
‰CHeight;
‰HPotRes,VPotRes;
‰LeftBorder;
‰TopBorder;
};€AUTOKNOB 1€FREEHORIZ 2€FREEVERT 4€PROPBORDERLESS 8€KNOBHIT 256€PROPNEWLOOK 16€KNOBHMIN 6€KNOBVMIN 4€MAXBODY 0xFFFF€MAXPOT 0xFFFF
ƒStringInfo
{
Š*Buffer;
Š*UndoBuffer;
˜BufferPos;
˜MaxChars;
˜DispPos;
˜UndoPos;
˜NumChars;
˜DispCount;
˜CLeft,CTop;
ƒStringExtend*Extension;
’LongInt;
ƒKeyMap*AltKeyMap;
};
ƒIntuiText
{
ŠFrontPen,BackPen;
ŠDrawMode;
˜LeftEdge;
˜TopEdge;
ƒTextAttr*ITextFont;
Š*IText;
ƒIntuiText*NextText;
};
ƒBorder
{
˜LeftEdge,TopEdge;
ŠFrontPen,BackPen;
ŠDrawMode;
šCount;
˜*XY;
ƒBorder*NextBorder;
};
ƒImage
{
˜LeftEdge;
˜TopEdge;
˜Width;
˜Height;
˜Depth;
‰*ImageData;
ŠPlanePick,PlaneOnOff;
ƒImage*NextImage;
};
ƒIntuiMessage
{
ƒ¯ExecMessage;
—Class;
‰Code;
‰Qualifier;
”IAddress;
˜MouseX,MouseY;
—Seconds,Micros;
ƒWindow*IDCMPWindow;
ƒIntuiMessage*SpecialLink;
};
ƒExtIntuiMessage
{
ƒIntuiMessage eim_IntuiMessage;
ƒTabletData*eim_TabletData;
};€IDCMP_SIZEVERIFY 1€IDCMP_NEWSIZE 2€IDCMP_REFRESHWINDOW 4€IDCMP_MOUSEBUTTONS 8€IDCMP_MOUSEMOVE 16€IDCMP_GADGETDOWN 32€IDCMP_GADGETUP 64€IDCMP_REQSET 128€IDCMP_MENUPICK 256€IDCMP_CLOSEWINDOW 512€IDCMP_RAWKEY 0x400€IDCMP_REQVERIFY 0x800€IDCMP_REQCLEAR 0x1000€IDCMP_MENUVERIFY 0x2000€IDCMP_NEWPREFS 0x4000€IDCMP_DISKINSERTED 0x8000€IDCMP_DISKREMOVED 0x10000€IDCMP_WBENCHMESSAGE 0x20000€IDCMP_ACTIVEWINDOW 0x40000€IDCMP_INACTIVEWINDOW 0x80000€IDCMP_DELTAMOVE 0x100000€IDCMP_VANILLAKEY 0x200000€IDCMP_INTUITICKS 0x400000€IDCMP_IDCMPUPDATE 0x800000€IDCMP_MENUHELP 0x1000000€IDCMP_CHANGEWINDOW 0x2000000€IDCMP_GADGETHELP 0x4000000€IDCMP_LONELYMESSAGE 0x80000000€CWCODE_MOVESIZE 0€CWCODE_DEPTH 1€MENUHOT 1€MENUCANCEL 2€MENUWAITING 3€OKOK MENUHOT€OKABORT 4€OKCANCEL MENUCANCEL€WBENCHOPEN 1€WBENCHCLOSE 2
ƒIBox
{
˜Left;
˜Top;
˜Width;
˜Height;
};
ƒWindow
{
ƒWindow*NextWindow;
˜LeftEdge,TopEdge;
˜Width,Height;
˜MouseY,MouseX;
˜MinWidth,MinHeight;
‰MaxWidth,MaxHeight;
—¦;
ƒMenu*MenuStrip;
Š*Title;
ƒRequester*FirstRequest;
ƒRequester*DMRequest;
˜ReqCount;
ƒScreen*WScreen;
ƒRastPort*RPort;
šBorderLeft,BorderTop,BorderRight,BorderBottom;
ƒRastPort*BorderRPort;
ƒ»*FirstGadget;
ƒWindow*Parent,*Descendant;
‰*Pointer;
šPtrHeight;
šPtrWidth;
šXOffset,YOffset;
—IDCMPFlags;
ƒ©*UserPort,*WindowPort;
ƒIntuiMessage*MessageKey;
ŠDetailPen,BlockPen;
ƒImage*CheckMark;
Š*ScreenTitle;
˜GZZMouseX;
˜GZZMouseY;
˜GZZWidth;
˜GZZHeight;
Š*ExtData;
š*UserData;
ƒLayer*WLayer;
ƒTextFont*IFont;
—MoreFlags;
};€WFLG_SIZEGADGET 1€WFLG_DRAGBAR 2€WFLG_DEPTHGADGET 4€WFLG_CLOSEGADGET 8€WFLG_SIZEBRIGHT 16€WFLG_SIZEBBOTTOM 32€WFLG_REFRESHBITS 192€WFLG_SMART_REFRESH 0€WFLG_SIMPLE_REFRESH 64€WFLG_SUPER_BITMAP 128€WFLG_OTHER_REFRESH 192€WFLG_BACKDROP 256€WFLG_REPORTMOUSE 512€WFLG_GIMMEZEROZERO 0x400€WFLG_BORDERLESS 0x800€WFLG_ACTIVATE 0x1000€WFLG_RMBTRAP 0x10000€WFLG_NOCAREREFRESH 0x20000€WFLG_NW_EXTENDED 0x40000€WFLG_NEWLOOKMENUS 0x200000€WFLG_WINDOWACTIVE 0x2000€WFLG_INREQUEST 0x4000€WFLG_MENUSTATE 0x8000€WFLG_WINDOWREFRESH 0x1000000€WFLG_WBENCHWINDOW 0x2000000€WFLG_WINDOWTICKED 0x4000000€WFLG_VISITOR 0x8000000€WFLG_ZOOMED 0x10000000€WFLG_HASZOOM 0x20000000€DEFAULTMOUSEQUEUE (5)
ƒNewWindow
{
˜LeftEdge,TopEdge;
˜Width,Height;
ŠDetailPen,BlockPen;
—IDCMPFlags;
—¦;
ƒ»*FirstGadget;
ƒImage*CheckMark;
Š*Title;
ƒScreen*Screen;
ƒBitMap*BitMap;
˜MinWidth,MinHeight;
‰MaxWidth,MaxHeight;
‰Type;
};
ƒExtNewWindow
{
˜LeftEdge,TopEdge;
˜Width,Height;
ŠDetailPen,BlockPen;
—IDCMPFlags;
—¦;
ƒ»*FirstGadget;
ƒImage*CheckMark;
Š*Title;
ƒScreen*Screen;
ƒBitMap*BitMap;
˜MinWidth,MinHeight;
‰MaxWidth,MaxHeight;
‰Type;
ƒTagItem*Extension;
};€WA_Dummy (TAG_USER+99)€WA_Left (WA_Dummy+1)€WA_Top (WA_Dummy+2)€WA_Width (WA_Dummy+3)€WA_Height (WA_Dummy+4)€WA_DetailPen (WA_Dummy+5)€WA_BlockPen (WA_Dummy+6)€WA_IDCMP (WA_Dummy+7)€WA_Flags (WA_Dummy+8)€WA_Gadgets (WA_Dummy+9)€WA_Checkmark (WA_Dummy+10)€WA_Title (WA_Dummy+11)€WA_ScreenTitle (WA_Dummy+12)€WA_CustomScreen (WA_Dummy+13)€WA_SuperBitMap (WA_Dummy+14)€WA_MinWidth (WA_Dummy+15)€WA_MinHeight (WA_Dummy+16)€WA_MaxWidth (WA_Dummy+17)€WA_MaxHeight (WA_Dummy+18)€WA_InnerWidth (WA_Dummy+19)€WA_InnerHeight (WA_Dummy+20)€WA_PubScreenName (WA_Dummy+21)€WA_PubScreen (WA_Dummy+22)€WA_PubScreenFallBack (WA_Dummy+23)€WA_WindowName (WA_Dummy+24)€WA_Colors (WA_Dummy+25)€WA_Zoom (WA_Dummy+26)€WA_MouseQueue (WA_Dummy+27)€WA_BackFill (WA_Dummy+28)€WA_RptQueue (WA_Dummy+29)€WA_SizeGadget (WA_Dummy+30)€WA_DragBar (WA_Dummy+31)€WA_DepthGadget (WA_Dummy+32)€WA_CloseGadget (WA_Dummy+33)€WA_Backdrop (WA_Dummy+34)€WA_ReportMouse (WA_Dummy+35)€WA_NoCareRefresh (WA_Dummy+36)€WA_Borderless (WA_Dummy+37)€WA_Activate (WA_Dummy+38)€WA_RMBTrap (WA_Dummy+39)€WA_WBenchWindow (WA_Dummy+40)€WA_SimpleRefresh (WA_Dummy+41)€WA_SmartRefresh (WA_Dummy+42)€WA_SizeBRight (WA_Dummy+43)€WA_SizeBBottom (WA_Dummy+44)€WA_AutoAdjust (WA_Dummy+45)€WA_GimmeZeroZero (WA_Dummy+46)€WA_MenuHelp (WA_Dummy+47)€WA_NewLookMenus (WA_Dummy+48)€WA_AmigaKey (WA_Dummy+49)€WA_NotifyDepth (WA_Dummy+50)€WA_Pointer (WA_Dummy+52)€WA_BusyPointer (WA_Dummy+53)€WA_PointerDelay (WA_Dummy+54)€WA_TabletMessages (WA_Dummy+55)€WA_HelpGroup (WA_Dummy+56)€WA_HelpGroupWindow (WA_Dummy+57)€HC_GADGETHELP (1)ˆINTUITION_SCREENS_HŒ<intuition/screens.h>‡ˆINTUITION_PREFERENCES_HŒ<intuition/preferences.h>‡
ƒRemember
{
ƒRemember*NextRemember;
—RememberSize;
Š*Memory;
};
ƒColorSpec
{
˜ColorIndex;
‰Red;
‰Green;
‰Blue;
};
ƒEasyStruct{
—es_StructSize;
—es_Flags;
Š*es_Title;
Š*es_TextFormat;
Š*es_GadgetFormat;
};€MENUNUM(n) (n&31)€ITEMNUM(n) ((n>>5)&63)€SUBNUM(n) ((n>>11)&31)€SHIFTMENU(n) (n&31)€SHIFTITEM(n) ((n&63)<<5)€SHIFTSUB(n) ((n&31)<<11)€FULLMENUNUM(menu,item,sub) \
(SHIFTSUB(sub)|SHIFTITEM(item)|SHIFTMENU(menu))€SRBNUM(n) (0x08-(n>>4))€SWBNUM(n) (0x08-(n&15))€SSBNUM(n) (0x01+(n>>4))€SPARNUM(n) (n>>4)€SHAKNUM(n) (n&15)€NOMENU 31€NOITEM 63€NOSUB 31€MENUNULL 0xFFFF€FOREVER for(;;)€SIGN(x) (((x)>0)-((x)<0))€NOT !€CHECKWIDTH 19€COMMWIDTH 27€LOWCHECKWIDTH 13€LOWCOMMWIDTH 16€ALERT_TYPE 0x80000000€RECOVERY_ALERT 0€DEADEND_ALERT 0x80000000€AUTOFRONTPEN 0€AUTOBACKPEN 1€AUTODRAWMODE JAM2€AUTOLEFTEDGE 6€AUTOTOPEDGE 3€AUTOITEXTFONTœ€AUTONEXTTEXTœ€SELECTUP (IECODE_LBUTTON|IECODE_UP_PREFIX)€SELECTDOWN (IECODE_LBUTTON)€MENUUP (IECODE_RBUTTON|IECODE_UP_PREFIX)€MENUDOWN (IECODE_RBUTTON)€MIDDLEUP (IECODE_MBUTTON|IECODE_UP_PREFIX)€MIDDLEDOWN (IECODE_MBUTTON)€ALTLEFT (IEQUALIFIER_LALT)€ALTRIGHT (IEQUALIFIER_RALT)€AMIGALEFT (IEQUALIFIER_LCOMMAND)€AMIGARIGHT (IEQUALIFIER_RCOMMAND)€AMIGAKEYS (AMIGALEFT|AMIGARIGHT)€CURSORUP 76€CURSORLEFT 79€CURSORRIGHT 78€CURSORDOWN 77€KEYCODE_Q 16€KEYCODE_Z 49€KEYCODE_X 50€KEYCODE_V 52€KEYCODE_B 53€KEYCODE_N 54€KEYCODE_M 55€KEYCODE_LESS 56€KEYCODE_GREATER 57€TABLETA_Dummy (TAG_USER+0x3A000)€TABLETA_TabletZ (TABLETA_Dummy+1)€TABLETA_RangeZ (TABLETA_Dummy+2)€TABLETA_AngleX (TABLETA_Dummy+3)€TABLETA_AngleY (TABLETA_Dummy+4)€TABLETA_AngleZ (TABLETA_Dummy+5)€TABLETA_Pressure (TABLETA_Dummy+6)€TABLETA_ButtonBits (TABLETA_Dummy+7)€TABLETA_InProximity (TABLETA_Dummy+8)€TABLETA_ResolutionX (TABLETA_Dummy+9)€TABLETA_ResolutionY (TABLETA_Dummy+10)
ƒTabletData
{
‰td_XFraction,td_YFraction;
—td_TabletX,td_TabletY;
—td_RangeX,td_RangeY;
ƒTagItem*td_TagList;
};
ƒTabletHookData
{
ƒScreen*thd_Screen;
—thd_Width;
—thd_Height;
’thd_ScreenChanged;
};ˆINTUITION_IOBSOLETE_HŒ<intuition/iobsolete.h>‡‡