€ˆRESOURCES_CARD_H€RESOURCES_CARD_H 1ˆEXEC_TYPES_HŒ"exec/types.h"‡ˆµŒ"exec/nodes.h"‡ˆEXEC_INTERRUPTS_HŒ"exec/interrupts.h"‡€CARDRESNAME "card.resource"
ƒCardHandle{
ƒ¬cah_CardNode;
ƒInterrupt*cah_CardRemoved;
ƒInterrupt*cah_CardInserted;
ƒInterrupt*cah_CardStatus;
Šcah_CardFlags;
};
ƒDeviceTData{
—dtd_DTsize;
—dtd_DTspeed;
Šdtd_DTtype;
Šdtd_DTflags;
};
ƒCardMemoryMap{
Š*cmm_CommonMemory;
Š*cmm_AttributeMemory;
Š*cmm_IOMemory;
—cmm_CommonMemSize;
—cmm_AttributeMemSize;
—cmm_IOMemSize;
};€CARDB_RESETREMOVE 0€CARDF_RESETREMOVE (1<<CARDB_RESETREMOVE)€CARDB_IFAVAILABLE 1€CARDF_IFAVAILABLE (1<<CARDB_IFAVAILABLE)€CARDB_DELAYOWNERSHIP 2€CARDF_DELAYOWNERSHIP (1<<CARDB_DELAYOWNERSHIP)€CARDB_POSTSTATUS 3€CARDF_POSTSTATUS (1<<CARDB_POSTSTATUS)€CARDB_REMOVEHANDLE 0€CARDF_REMOVEHANDLE (1<<CARDB_REMOVEHANDLE)€CARD_STATUSB_CCDET 6€CARD_STATUSF_CCDET (1<<CARD_STATUSB_CCDET)€CARD_STATUSB_BVD1 5€CARD_STATUSF_BVD1 (1<<CARD_STATUSB_BVD1)€CARD_STATUSB_SC 5€CARD_STATUSF_SC (1<<CARD_STATUSB_SC)€CARD_STATUSB_BVD2 4€CARD_STATUSF_BVD2 (1<<CARD_STATUSB_BVD2)€CARD_STATUSB_DA 4€CARD_STATUSF_DA (1<<CARD_STATUSB_DA)€CARD_STATUSB_WR 3€CARD_STATUSF_WR (1<<CARD_STATUSB_WR)€CARD_STATUSB_BSY 2€CARD_STATUSF_BSY (1<<CARD_STATUSB_BSY)€CARD_STATUSB_IRQ 2€CARD_STATUSF_IRQ (1<<CARD_STATUSB_IRQ)€CARD_VOLTAGE_0V 0€CARD_VOLTAGE_5V 1€CARD_VOLTAGE_12V 2€CARD_ENABLEB_DIGAUDIO 1€CARD_ENABLEF_DIGAUDIO (1<<CARD_ENABLEB_DIGAUDIO)€CARD_DISABLEB_WP 3€CARD_DISABLEF_WP (1<<CARD_DISABLEB_WP)€CARD_INTB_SETCLR 7€CARD_INTF_SETCLR (1<<CARD_INTB_SETCLR)€CARD_INTB_BVD1 5€CARD_INTF_BVD1 (1<<CARD_INTB_BVD1)€CARD_INTB_SC 5€CARD_INTF_SC (1<<CARD_INTB_SC)€CARD_INTB_BVD2 4€CARD_INTF_BVD2 (1<<CARD_INTB_BVD2)€CARD_INTB_DA 4€CARD_INTF_DA (1<<CARD_INTB_DA)€CARD_INTB_BSY 2€CARD_INTF_BSY (1<<CARD_INTB_BSY)€CARD_INTB_IRQ 2€CARD_INTF_IRQ (1<<CARD_INTB_IRQ)€CARD_INTERFACE_AMIGA_0 0€CISTPL_AMIGAXIP 145
ƒTP_AmigaXIP{
ŠTPL_CODE;
ŠTPL_LINK;
ŠTP_XIPLOC[4];
ŠTP_XIPFLAGS;
ŠTP_XIPRESRV;
};€XIPFLAGSB_AUTORUN 0€XIPFLAGSF_AUTORUN (1<<XIPFLAGSB_AUTORUN)‡