Äà_FCTYPE_HÄ_FCTYPE_H 1å<sys/commargs.h>
ÅÇisupper __ARGS((Ç));
ÅÇislower __ARGS((Ç));
ÅÇisdigit __ARGS((Ç));
ÅÇisxdigit __ARGS((Ç));
ÅÇisspace __ARGS((Ç));
ÅÇispunct __ARGS((Ç));
ÅÇisalpha __ARGS((Ç));
ÅÇisalnum __ARGS((Ç));
ÅÇisprint __ARGS((Ç));
ÅÇisgraph __ARGS((Ç));
ÅÇiscntrl __ARGS((Ç));
ÅÇisascii __ARGS((Ç));
ÅÇiscsym __ARGS((Ç));
ÅÇiscsymf __ARGS((Ç));
ÅÇtoupper __ARGS((Ç));
ÅÇtolower __ARGS((Ç));
ÅÇtoascii __ARGS((Ç));å<sys/commnull.h>á