€ˆ_STRING_H€_STRING_H 1Œ<sys/commsize.h>Œ<sys/commnull.h>
‹*memcpy(‹*,const‹*,size_t);
‹*memmove(‹*,const‹*,size_t);
„*strcpy(„*,const„*);
„*strncpy(„*,const„*,size_t);
„*strcat(„*,const„*);
„*strncat(„*,const„*,size_t);
‚memcmp(const‹*,const‹*,size_t);
‚strcmp(const„*,const„*);
‚strcoll(const„*,const„*);
‚strncmp(const„*,const„*,size_t);
size_t strxfrm(„*,const„*,size_t);
‹*memchr(const‹*,‚,size_t);
„*strchr(const„*,‚);
size_t strcspn(const„*,const„*);
„*strpbrk(const„*,const„*);
„*strrchr(const„*,‚);
size_t strspn(const„*,const„*);
„*strstr(const„*,const„*);
„*strtok(„*,const„*);
‹*memset(‹*,‚,size_t);
„*strerror(‚);
size_t strlen(const„*);ˆ_STRICT_ANSI
‚stcarg(const„*,const„*);
‚stccpy(„*,const„*,‚);
‚stcgfe(„*,const„*);
‚stcgfn(„*,const„*);
‚stcis(const„*,const„*);
‚stcisn(const„*,const„*);
‚__stcd_i(const„*,‚*);
‚__stcd_l(const„*,*);
‚stch_i(const„*,‚*);
‚stch_l(const„*,*);
‚stci_d(„*,‚);
‚stci_h(„*,‚);
‚stci_o(„*,‚);
‚stcl_d(„*,);
‚__stcl_h(„*,);
‚__stcl_o(„*,);
‚stco_i(const„*,‚*);
‚stco_l(const„*,*);
‚stcpm(const„*,const„*,„**);
‚stcpma(const„*,const„*);
‚stcsma(const„*,const„*);
‚astcsma(const„*,const„*);
‚stcu_d(„*,);
‚__stcul_d(„*,);€stclen(a) strlen(a)
„*stpblk(const„*);
„*stpbrk(const„*,const„*);
„*stpchr(const„*,‚);
„*stpcpy(„*,const„*);
„*__stpcpy(„*,const„*);
„*stpdate(„*,‚,const„*);
„*stpsym(const„*,„*,‚);
„*stptime(„*,‚,const„*);
„*stptok(const„*,„*,‚,const„*);
‚strbpl(„**,‚,const„*);
‚stricmp(const„*,const„*);
„*strdup(const„*);
‹strins(„*,const„*);
‚strmid(const„*,„*,‚,‚);
„*__strlwr(„*);
‹strmfe(„*,const„*,const„*);
‹strmfn(„*,const„*,const„*,const„*,
const„*);
‹strmfp(„*,const„*,const„*);
‚strnicmp(const„*,const„*,size_t);
„*strnset(„*,‚,‚);
„*stpchrn(const„*,‚);
„*strrev(„*);
„*strset(„*,‚);
‹strsfn(const„*,„*,„*,„*,„*);
„*__strupr(„*);
‚stspfp(„*,‚*);
‹strsrt(„*[],‚);
‚stcgfp(„*,const„*);€strcmpi stricmp€strlwr __strlwr€strupr __strupr€stcd_i __stcd_i€stcd_l __stcd_l€stcl_h __stcl_h€stcl_o __stcl_o€stcul_d __stcul_d€stpcpy __stpcpy
‹*memccpy(‹*,const‹*,‚,);
‹movmem(const‹*,‹*,);
‹repmem(‹*,const‹*,size_t,size_t);
‹setmem(‹*,,‚);
‹__swmem(‹*,‹*,);€swmem __swmem€index(a,b) strchr(a,b)€rindex(a,b) strrchr(a,b)€bcopy(a,b,c) memmove(b,a,c)€bcmp(a,b,c) memcmp(a,b,c)€bzero(a,b) memset(a,0,b)‡
size_t __builtin_strlen(const„*);
‚__builtin_strcmp(const„*,const„*);
„*__builtin_strcpy(„*,const„*);
‹*__builtin_memset(‹*,‚,size_t);
‚__builtin_memcmp(const‹*,const‹*,size_t);
‹*__builtin_memcpy(‹*,const‹*,size_t);
‚__builtin_max(‚,‚);
‚__builtin_min(‚,‚);
‚__builtin_abs(‚);°USE_BUILTIN_MATH€_FROM_STRING_H 1Œ<sys/commmacs.h>‡€strlen(a) __builtin_strlen(a)€strcmp(a,b) __builtin_strcmp(a,b)€strcpy(a,b) __builtin_strcpy(a,b)€memset(a,b,c) __builtin_memset(a,b,c)€memcmp(a,b,c) __builtin_memcmp(a,b,c)€memcpy(a,b,c) __builtin_memcpy(a,b,c)‡