€ˆLIBRARIES_ASL_H€LIBRARIES_ASL_HˆEXEC_TYPES_HŒ<exec/types.h>‡ˆµŒ<exec/nodes.h>‡ˆUTILITY_TAGITEM_HŒ<utility/tagitem.h>‡ˆWORKBENCH_STARTUP_HŒ<workbench/startup.h>‡ˆGRAPHICS_TEXT_HŒ<graphics/text.h>‡ˆGRAPHICS_DISPLAYINFO_HŒ<graphics/displayinfo.h>‡€AslName "asl.library"€ASL_TB (TAG_USER+0x80000)€ASL_FileRequest 0€ASL_FontRequest 1€ASL_ScreenModeRequest 2
ƒFileRequester
{
Šfr_Reserved0[4];
STRPTR fr_File;
STRPTR fr_Drawer;
Šfr_Reserved1[10];
˜fr_LeftEdge;
˜fr_TopEdge;
˜fr_Width;
˜fr_Height;
Šfr_Reserved2[2];
’fr_NumArgs;
ƒWBArg*fr_ArgList;
”fr_UserData;
Šfr_Reserved3[8];
STRPTR fr_Pattern;
};€ASLFR_Window ASL_TB+2€ASLFR_Screen ASL_TB+40€ASLFR_PubScreenName ASL_TB+41€ASLFR_PrivateIDCMP ASL_TB+42€ASLFR_IntuiMsgFunc ASL_TB+70€ASLFR_SleepWindow ASL_TB+43€ASLFR_UserData ASL_TB+52€ASLFR_TextAttr ASL_TB+51€ASLFR_Locale ASL_TB+50€ASLFR_TitleText ASL_TB+1€ASLFR_PositiveText ASL_TB+18€ASLFR_NegativeText ASL_TB+19€ASLFR_InitialLeftEdge ASL_TB+3€ASLFR_InitialTopEdge ASL_TB+4€ASLFR_InitialWidth ASL_TB+5€ASLFR_InitialHeight ASL_TB+6€ASLFR_InitialFile ASL_TB+8€ASLFR_InitialDrawer ASL_TB+9€ASLFR_InitialPattern ASL_TB+10€ASLFR_Flags1 ASL_TB+20€ASLFR_Flags2 ASL_TB+22€ASLFR_DoSaveMode ASL_TB+44€ASLFR_DoMultiSelect ASL_TB+45€ASLFR_DoPatterns ASL_TB+46€ASLFR_DrawersOnly ASL_TB+47€ASLFR_FilterFunc ASL_TB+49€ASLFR_RejectIcons ASL_TB+60€ASLFR_RejectPattern ASL_TB+61€ASLFR_AcceptPattern ASL_TB+62€ASLFR_FilterDrawers ASL_TB+63€ASLFR_HookFunc ASL_TB+7€FRB_FILTERFUNC 7€FRB_INTUIFUNC 6€FRB_DOSAVEMODE 5€FRB_PRIVATEIDCMP 4€FRB_DOMULTISELECT 3€FRB_DOPATTERNS 0€FRF_FILTERFUNC (1L<<FRB_FILTERFUNC)€FRF_INTUIFUNC (1L<<FRB_INTUIFUNC)€FRF_DOSAVEMODE (1L<<FRB_DOSAVEMODE)€FRF_PRIVATEIDCMP (1L<<FRB_PRIVATEIDCMP)€FRF_DOMULTISELECT (1L<<FRB_DOMULTISELECT)€FRF_DOPATTERNS (1L<<FRB_DOPATTERNS)€FRB_DRAWERSONLY 0€FRB_FILTERDRAWERS 1€FRB_REJECTICONS 2€FRF_DRAWERSONLY (1L<<FRB_DRAWERSONLY)€FRF_FILTERDRAWERS (1L<<FRB_FILTERDRAWERS)€FRF_REJECTICONS (1L<<FRB_REJECTICONS)
ƒFontRequester
{
Šfo_Reserved0[8];
ƒTextAttr fo_Attr;
Šfo_FrontPen;
Šfo_BackPen;
Šfo_DrawMode;
Šfo_Reserved1;
”fo_UserData;
˜fo_LeftEdge;
˜fo_TopEdge;
˜fo_Width;
˜fo_Height;
ƒTTextAttr fo_TAttr;
};€ASLFO_Window ASL_TB+2€ASLFO_Screen ASL_TB+40€ASLFO_PubScreenName ASL_TB+41€ASLFO_PrivateIDCMP ASL_TB+42€ASLFO_IntuiMsgFunc ASL_TB+70€ASLFO_SleepWindow ASL_TB+43€ASLFO_UserData ASL_TB+52€ASLFO_TextAttr ASL_TB+51€ASLFO_Locale ASL_TB+50€ASLFO_TitleText ASL_TB+1€ASLFO_PositiveText ASL_TB+18€ASLFO_NegativeText ASL_TB+19€ASLFO_InitialLeftEdge ASL_TB+3€ASLFO_InitialTopEdge ASL_TB+4€ASLFO_InitialWidth ASL_TB+5€ASLFO_InitialHeight ASL_TB+6€ASLFO_InitialName ASL_TB+10€ASLFO_InitialSize ASL_TB+11€ASLFO_InitialStyle ASL_TB+12€ASLFO_InitialFlags ASL_TB+13€ASLFO_InitialFrontPen ASL_TB+14€ASLFO_InitialBackPen ASL_TB+15€ASLFO_InitialDrawMode ASL_TB+59€ASLFO_Flags ASL_TB+20€ASLFO_DoFrontPen ASL_TB+44€ASLFO_DoBackPen ASL_TB+45€ASLFO_DoStyle ASL_TB+46€ASLFO_DoDrawMode ASL_TB+47€ASLFO_FixedWidthOnly ASL_TB+48€ASLFO_MinHeight ASL_TB+16€ASLFO_MaxHeight ASL_TB+17€ASLFO_FilterFunc ASL_TB+49€ASLFO_HookFunc ASL_TB+7€ASLFO_MaxFrontPen ASL_TB+66€ASLFO_MaxBackPen ASL_TB+67€ASLFO_ModeList ASL_TB+21€ASLFO_FrontPens ASL_TB+64€ASLFO_BackPens ASL_TB+65€FOB_DOFRONTPEN 0€FOB_DOBACKPEN 1€FOB_DOSTYLE 2€FOB_DODRAWMODE 3€FOB_FIXEDWIDTHONLY 4€FOB_PRIVATEIDCMP 5€FOB_INTUIFUNC 6€FOB_FILTERFUNC 7€FOF_DOFRONTPEN (1L<<FOB_DOFRONTPEN)€FOF_DOBACKPEN (1L<<FOB_DOBACKPEN)€FOF_DOSTYLE (1L<<FOB_DOSTYLE)€FOF_DODRAWMODE (1L<<FOB_DODRAWMODE)€FOF_FIXEDWIDTHONLY (1L<<FOB_FIXEDWIDTHONLY)€FOF_PRIVATEIDCMP (1L<<FOB_PRIVATEIDCMP)€FOF_INTUIFUNC (1L<<FOB_INTUIFUNC)€FOF_FILTERFUNC (1L<<FOB_FILTERFUNC)
ƒScreenModeRequester
{
—sm_DisplayID;
—sm_DisplayWidth;
—sm_DisplayHeight;
‰sm_DisplayDepth;
‰sm_OverscanType;
BOOL sm_AutoScroll;
—sm_BitMapWidth;
—sm_BitMapHeight;
˜sm_LeftEdge;
˜sm_TopEdge;
˜sm_Width;
˜sm_Height;
BOOL sm_InfoOpened;
˜sm_InfoLeftEdge;
˜sm_InfoTopEdge;
˜sm_InfoWidth;
˜sm_InfoHeight;
”sm_UserData;
};
ƒDisplayMode
{
ƒ¬dm_Node;
ƒDimensionInfo dm_DimensionInfo;
—dm_PropertyFlags;
};€ASLSM_Window ASL_TB+2€ASLSM_Screen ASL_TB+40€ASLSM_PubScreenName ASL_TB+41€ASLSM_PrivateIDCMP ASL_TB+42€ASLSM_IntuiMsgFunc ASL_TB+70€ASLSM_SleepWindow ASL_TB+43€ASLSM_UserData ASL_TB+52€ASLSM_TextAttr ASL_TB+51€ASLSM_Locale ASL_TB+50€ASLSM_TitleText ASL_TB+1€ASLSM_PositiveText ASL_TB+18€ASLSM_NegativeText ASL_TB+19€ASLSM_InitialLeftEdge ASL_TB+3€ASLSM_InitialTopEdge ASL_TB+4€ASLSM_InitialWidth ASL_TB+5€ASLSM_InitialHeight ASL_TB+6€ASLSM_InitialDisplayID ASL_TB+100€ASLSM_InitialDisplayWidth ASL_TB+101€ASLSM_InitialDisplayHeight ASL_TB+102€ASLSM_InitialDisplayDepth ASL_TB+103€ASLSM_InitialOverscanType ASL_TB+104€ASLSM_InitialAutoScroll ASL_TB+105€ASLSM_InitialInfoOpened ASL_TB+106€ASLSM_InitialInfoLeftEdge ASL_TB+107€ASLSM_InitialInfoTopEdge ASL_TB+108€ASLSM_DoWidth ASL_TB+109€ASLSM_DoHeight ASL_TB+110€ASLSM_DoDepth ASL_TB+111€ASLSM_DoOverscanType ASL_TB+112€ASLSM_DoAutoScroll ASL_TB+113€ASLSM_PropertyFlags ASL_TB+114€ASLSM_PropertyMask ASL_TB+115€ASLSM_MinWidth ASL_TB+116€ASLSM_MaxWidth ASL_TB+117€ASLSM_MinHeight ASL_TB+118€ASLSM_MaxHeight ASL_TB+119€ASLSM_MinDepth ASL_TB+120€ASLSM_MaxDepth ASL_TB+121€ASLSM_FilterFunc ASL_TB+122€ASLSM_CustomSMList ASL_TB+123ˆASL_V38_NAMES_ONLY€rf_File fr_File€rf_Dir fr_Drawer€rf_LeftEdge fr_LeftEdge€rf_TopEdge fr_TopEdge€rf_Width fr_Width€rf_Height fr_Height€rf_NumArgs fr_NumArgs€rf_ArgList fr_ArgList€rf_UserData fr_UserData€rf_Pat fr_Pattern€ASL_Dummy (TAG_USER+0x80000)€ASL_Hail ASL_Dummy+1€ASL_Window ASL_Dummy+2€ASL_LeftEdge ASL_Dummy+3€ASL_TopEdge ASL_Dummy+4€ASL_Width ASL_Dummy+5€ASL_Height ASL_Dummy+6€ASL_HookFunc ASL_Dummy+7€ASL_File ASL_Dummy+8€ASL_Dir ASL_Dummy+9€ASL_FontName ASL_Dummy+10€ASL_FontHeight ASL_Dummy+11€ASL_FontStyles ASL_Dummy+12€ASL_FontFlags ASL_Dummy+13€ASL_FrontPen ASL_Dummy+14€ASL_BackPen ASL_Dummy+15€ASL_MinHeight ASL_Dummy+16€ASL_MaxHeight ASL_Dummy+17€ASL_OKText ASL_Dummy+18€ASL_CancelText ASL_Dummy+19€ASL_FuncFlags ASL_Dummy+20€ASL_ModeList ASL_Dummy+21€ASL_ExtFlags1 ASL_Dummy+22€ASL_Pattern ASL_FontName€FILB_DOWILDFUNC 7L€FILB_DOMSGFUNC 6L€FILB_SAVE 5L€FILB_NEWIDCMP 4L€FILB_MULTISELECT 3L€FILB_PATGAD 0L€FILF_DOWILDFUNC (1L<<FILB_DOWILDFUNC)€FILF_DOMSGFUNC (1L<<FILB_DOMSGFUNC)€FILF_SAVE (1L<<FILB_SAVE)€FILF_NEWIDCMP (1L<<FILB_NEWIDCMP)€FILF_MULTISELECT (1L<<FILB_MULTISELECT)€FILF_PATGAD (1L<<FILB_PATGAD)€FIL1B_NOFILES 0L€FIL1B_MATCHDIRS 1L€FIL1F_NOFILES (1L<<FIL1B_NOFILES)€FIL1F_MATCHDIRS (1L<<FIL1B_MATCHDIRS)€FONB_FRONTCOLOR 0€FONB_BACKCOLOR 1€FONB_STYLES 2€FONB_DRAWMODE 3€FONB_FIXEDWIDTH 4€FONB_NEWIDCMP 5€FONB_DOMSGFUNC 6€FONB_DOWILDFUNC 7€FONF_FRONTCOLOR (1L<<FONB_FRONTCOLOR)€FONF_BACKCOLOR (1L<<FONB_BACKCOLOR)€FONF_STYLES (1L<<FONB_STYLES)€FONF_DRAWMODE (1L<<FONB_DRAWMODE)€FONF_FIXEDWIDTH (1L<<FONB_FIXEDWIDTH)€FONF_NEWIDCMP (1L<<FONB_NEWIDCMP)€FONF_DOMSGFUNC (1L<<FONB_DOMSGFUNC)€FONF_DOWILDFUNC (1L<<FONB_DOWILDFUNC)‡‡