€ˆLIBRARIES_COMMODITIES_H€LIBRARIES_COMMODITIES_HˆEXEC_TYPES_HŒ<exec/types.h>‡ˆ¸Œ<exec/ports.h>‡€CxFilter(d) CreateCxObj((’)CX_FILTER,(’)d,0)€CxSender(port,id) CreateCxObj((’)CX_SEND,(’)port,(’)id)€CxSignal(task,sig) CreateCxObj((’)CX_SIGNAL,(’)task,(’)sig)€CxTranslate(ie) CreateCxObj((’)CX_TRANSLATE,(’)ie,0)€CxDebug(id) CreateCxObj((’)CX_DEBUG,(’)id,0)€CxCustom(action,id) CreateCxObj((’)CX_CUSTOM,(’)action,(’)id)
ƒNewBroker
{
šnb_Version;
STRPTR nb_Name;
STRPTR nb_Title;
STRPTR nb_Descr;
˜nb_Unique;
˜nb_Flags;
šnb_Pri;
ƒ©*nb_Port;
˜nb_ReservedChannel;
};€NB_VERSION 5€CBD_NAMELEN 24€CBD_TITLELEN 40€CBD_DESCRLEN 40€NBU_DUPLICATE 0€NBU_UNIQUE 1€NBU_NOTIFY 2€COF_SHOW_HIDE 4ˆCOMMODITIES_BASE_H
¥’CxObj;
¥’CxMsg;‡
¥’(*PFL)();€CX_INVALID 0€CX_FILTER 1€CX_TYPEFILTER 2€CX_SEND 3€CX_SIGNAL 4€CX_TRANSLATE 5€CX_BROKER 6€CX_DEBUG 7€CX_CUSTOM 8€CX_ZERO 9€CXM_IEVENT (1<<5)€CXM_COMMAND (1<<6)€CXCMD_DISABLE (15)€CXCMD_ENABLE (17)€CXCMD_APPEAR (19)€CXCMD_DISAPPEAR (21)€CXCMD_KILL (23)€CXCMD_LIST_CHG (27)€CXCMD_UNIQUE (25)
ƒInputXpression
{
Šix_Version;
Šix_Class;
‰ix_Code;
‰ix_CodeMask;
‰ix_Qualifier;
‰ix_QualMask;
‰ix_QualSame;
};
¥ƒInputXpression IX;€IX_VERSION 2€IXSYM_SHIFT 1€IXSYM_CAPS 2€IXSYM_ALT 4€IXSYM_SHIFTMASK (IEQUALIFIER_LSHIFT|IEQUALIFIER_RSHIFT)€IXSYM_CAPSMASK (IXSYM_SHIFTMASK|IEQUALIFIER_CAPSLOCK)€IXSYM_ALTMASK (IEQUALIFIER_LALT|IEQUALIFIER_RALT)€IX_NORMALQUALS 0x7FFF€NULL_IX(ix) ((ix)->ix_Class==IECLASS_NULL)€CBERR_OK 0€CBERR_SYSERR 1€CBERR_DUP 2€CBERR_VERSION 3€COERR_ISNULL 1€COERR_NULLATTACH 2€COERR_BADFILTER 4€COERR_BADTYPE 8‡