€ˆLIBRARIES_EXPANSIONBASE_H€LIBRARIES_EXPANSIONBASE_HˆEXEC_TYPES_HŒ"exec/types.h"‡ˆEXEC_LIBRARIES_HŒ"exec/libraries.h"‡ˆEXEC_SEMAPHORES_HŒ"exec/semaphores.h"‡ˆLIBRARIES_CONFIGVARS_HŒ"libraries/configvars.h"‡
ƒBootNode
{
ƒ¬bn_Node;
‰bn_Flags;
”bn_DeviceNode;
};
ƒ­
{
ƒLibrary LibNode;
Š¦;
Šeb_Private01;
—eb_Private02;
—eb_Private03;
ƒCurrentBinding eb_Private04;
ƒ®eb_Private05;
ƒ®MountList;
};€EE_OK 0€EE_LASTBOARD 40€EE_NOEXPANSION 41€EE_NOMEMORY 42€EE_NOBOARD 43€EE_BADMEM 44€EBB_CLOGGED 0€EBF_CLOGGED (1<<0)€EBB_SHORTMEM 1€EBF_SHORTMEM (1<<1)€EBB_BADMEM 2€EBF_BADMEM (1<<2)€EBB_DOSFLAG 3€EBF_DOSFLAG (1<<3)€EBB_KICKBACK33 4€EBF_KICKBACK33 (1<<4)€EBB_KICKBACK36 5€EBF_KICKBACK36 (1<<5)€EBB_SILENTSTART 6€EBF_SILENTSTART (1<<6)€EBB_START_CC0 7€EBF_START_CC0 (1<<7)‡