€ˆLIBRARIES_GADTOOLS_H€LIBRARIES_GADTOOLS_HˆEXEC_TYPES_HŒ<exec/types.h>‡ˆUTILITY_TAGITEM_HŒ<utility/tagitem.h>‡ˆINTUITION_INTUITION_HŒ<intuition/intuition.h>‡€GENERIC_KIND 0€BUTTON_KIND 1€CHECKBOX_KIND 2€INTEGER_KIND 3€LISTVIEW_KIND 4€MX_KIND 5€NUMBER_KIND 6€CYCLE_KIND 7€PALETTE_KIND 8€SCROLLER_KIND 9€SLIDER_KIND 11€STRING_KIND 12€TEXT_KIND 13€NUM_KINDS 14€ARROWIDCMP (IDCMP_GADGETUP|IDCMP_GADGETDOWN|\
IDCMP_INTUITICKS|IDCMP_MOUSEBUTTONS)€BUTTONIDCMP (IDCMP_GADGETUP)€CHECKBOXIDCMP (IDCMP_GADGETUP)€INTEGERIDCMP (IDCMP_GADGETUP)€LISTVIEWIDCMP (IDCMP_GADGETUP|IDCMP_GADGETDOWN|\
IDCMP_MOUSEMOVE|ARROWIDCMP)€MXIDCMP (IDCMP_GADGETDOWN)€NUMBERIDCMP (0L)€CYCLEIDCMP (IDCMP_GADGETUP)€PALETTEIDCMP (IDCMP_GADGETUP)€SCROLLERIDCMP (IDCMP_GADGETUP|IDCMP_GADGETDOWN|IDCMP_MOUSEMOVE)€SLIDERIDCMP (IDCMP_GADGETUP|IDCMP_GADGETDOWN|IDCMP_MOUSEMOVE)€STRINGIDCMP (IDCMP_GADGETUP)€TEXTIDCMP (0L)
ƒNewGadget
{
˜ng_LeftEdge,ng_TopEdge;
˜ng_Width,ng_Height;
Š*ng_GadgetText;
ƒTextAttr*ng_TextAttr;
‰ng_GadgetID;
—ng_Flags;
”ng_VisualInfo;
”ng_UserData;
};€PLACETEXT_LEFT 1€PLACETEXT_RIGHT 2€PLACETEXT_ABOVE 4€PLACETEXT_BELOW 8€PLACETEXT_IN 16€NG_HIGHLABEL 32
ƒNewMenu
{
Šnm_Type;
STRPTR nm_Label;
STRPTR nm_CommKey;
‰nm_Flags;
’nm_MutualExclude;
”nm_UserData;
};€MENU_IMAGE 128€NM_TITLE 1€NM_ITEM 2€NM_SUB 3€IM_ITEM (NM_ITEM|MENU_IMAGE)€IM_SUB (NM_SUB|MENU_IMAGE)€NM_END 0€NM_IGNORE 64€NM_BARLABEL ((STRPTR)-1)€NM_MENUDISABLED MENUENABLED€NM_ITEMDISABLED ITEMENABLED€NM_COMMANDSTRING COMMSEQ€NM_FLAGMASK (~(COMMSEQ|ITEMTEXT|HIGHFLAGS))€NM_FLAGMASK_V39 (~(ITEMTEXT|HIGHFLAGS))€GTMENU_USERDATA(menu) (*((”*)(((ƒMenu*)menu)+1)))€GTMENUITEM_USERDATA(menuitem) (*((”*)(((ƒMenuItem*)menuitem)+1)))€MENU_USERDATA(menuitem) (*((”*)(menuitem+1)))€GTMENU_TRIMMED 1€GTMENU_INVALID 2€GTMENU_NOMEM 3€MX_WIDTH 17€MX_HEIGHT 9€CHECKBOX_WIDTH 26€CHECKBOX_HEIGHT 11€GT_TagBase TAG_USER+0x80000€GTVI_NewWindow GT_TagBase+1€GTVI_NWTags GT_TagBase+2€GT_Private0 GT_TagBase+3€GTCB_Checked GT_TagBase+4€GTLV_Top GT_TagBase+5€GTLV_Labels GT_TagBase+6€GTLV_ReadOnly GT_TagBase+7€GTLV_ScrollWidth GT_TagBase+8€GTMX_Labels GT_TagBase+9€GTMX_Active GT_TagBase+10€GTTX_Text GT_TagBase+11€GTTX_CopyText GT_TagBase+12€GTNM_Number GT_TagBase+13€GTCY_Labels GT_TagBase+14€GTCY_Active GT_TagBase+15€GTPA_Depth GT_TagBase+16€GTPA_Color GT_TagBase+17€GTPA_ColorOffset GT_TagBase+18€GTPA_IndicatorWidth GT_TagBase+19€GTPA_IndicatorHeight GT_TagBase+20€GTSC_Top GT_TagBase+21€GTSC_Total GT_TagBase+22€GTSC_Visible GT_TagBase+23€GTSC_Overlap GT_TagBase+24€GTSL_Min GT_TagBase+38€GTSL_Max GT_TagBase+39€GTSL_Level GT_TagBase+40€GTSL_MaxLevelLen GT_TagBase+41€GTSL_LevelFormat GT_TagBase+42€GTSL_LevelPlace GT_TagBase+43€GTSL_DispFunc GT_TagBase+44€GTST_String GT_TagBase+45€GTST_MaxChars GT_TagBase+46€GTIN_Number GT_TagBase+47€GTIN_MaxChars GT_TagBase+48€GTMN_TextAttr GT_TagBase+49€GTMN_FrontPen GT_TagBase+50€GTBB_Recessed GT_TagBase+51€GT_VisualInfo GT_TagBase+52€GTLV_ShowSelected GT_TagBase+53€GTLV_Selected GT_TagBase+54€GT_Reserved1 GT_TagBase+56€GTTX_Border GT_TagBase+57€GTNM_Border GT_TagBase+58€GTSC_Arrows GT_TagBase+59€GTMN_Menu GT_TagBase+60€GTMX_Spacing GT_TagBase+61€GTMN_FullMenu GT_TagBase+62€GTMN_SecondaryError GT_TagBase+63€GT_Underscore GT_TagBase+64€GTST_EditHook GT_TagBase+55€GTIN_EditHook GTST_EditHook€GTMN_Checkmark GT_TagBase+65€GTMN_AmigaKey GT_TagBase+66€GTMN_NewLookMenus GT_TagBase+67€GTCB_Scaled GT_TagBase+68€GTMX_Scaled GT_TagBase+69€GTPA_NumColors GT_TagBase+70€GTMX_TitlePlace GT_TagBase+71€GTTX_FrontPen GT_TagBase+72€GTTX_BackPen GT_TagBase+73€GTTX_Justification GT_TagBase+74€GTNM_FrontPen GT_TagBase+72€GTNM_BackPen GT_TagBase+73€GTNM_Justification GT_TagBase+74€GTNM_Format GT_TagBase+75€GTNM_MaxNumberLen GT_TagBase+76€GTBB_FrameType GT_TagBase+77€GTLV_MakeVisible GT_TagBase+78€GTLV_ItemHeight GT_TagBase+79€GTSL_MaxPixelLen GT_TagBase+80€GTSL_Justification GT_TagBase+81€GTPA_ColorTable GT_TagBase+82€GTLV_CallBack GT_TagBase+83€GTLV_MaxPen GT_TagBase+84€GTTX_Clipped GT_TagBase+85€GTNM_Clipped GT_TagBase+85€GT_Reserved0 GTST_EditHook€GTJ_LEFT 0€GTJ_RIGHT 1€GTJ_CENTER 2€BBFT_BUTTON 1€BBFT_RIDGE 2€BBFT_ICONDROPBOX 3€INTERWIDTH 8€INTERHEIGHT 4€NWAY_KIND CYCLE_KIND€NWAYIDCMP CYCLEIDCMP€GTNW_Labels GTCY_Labels€GTNW_Active GTCY_Active€GADTOOLBIT (0x8000)€GADTOOLMASK (~GADTOOLBIT)€LV_DRAW 514L€LVCB_OK 0€LVCB_UNKNOWN 1€LVR_NORMAL 0€LVR_SELECTED 1€LVR_NORMALDISABLED 2€LVR_SELECTEDDISABLED 8
ƒLVDrawMsg
{
—lvdm_MethodID;
ƒRastPort*lvdm_RastPort;
ƒDrawInfo*lvdm_DrawInfo;
ƒRectangle lvdm_Bounds;
—lvdm_State;
};‡