€ˆDOS_VAR_H€DOS_VAR_HˆµŒ"exec/nodes.h"‡
ƒLocalVar{
ƒ¬lv_Node;
‰lv_Flags;
Š*lv_Value;
—lv_Len;
};€LV_VAR 0€LV_ALIAS 1€LVB_IGNORE 7€LVF_IGNORE 128€GVB_GLOBAL_ONLY 8€GVF_GLOBAL_ONLY 256€GVB_LOCAL_ONLY 9€GVF_LOCAL_ONLY 512€GVB_BINARY_VAR 10€GVF_BINARY_VAR 0x400€GVB_DONT_NULL_TERM 11€GVF_DONT_NULL_TERM 0x800€GVB_SAVE_VAR 12€GVF_SAVE_VAR 0x1000‡