€ˆPREFS_PRINTERPS_H€PREFS_PRINTERPS_HˆEXEC_TYPES_HŒ<exec/types.h>‡ˆLIBRARIES_IFFPARSE_HŒ<libraries/iffparse.h>‡€ID_PSPD MAKE_ID('P','S','P','D')
ƒPrinterPSPrefs
{
’ps_Reserved[4];
Šps_DriverMode;
Šps_PaperFormat;
Šps_Reserved1[2];
’ps_Copies;
’ps_PaperWidth;
’ps_PaperHeight;
’ps_HorizontalDPI;
’ps_VerticalDPI;
Šps_Font;
Šps_Pitch;
Šps_Orientation;
Šps_Tab;
Šps_Reserved2[8];
’ps_LeftMargin;
’ps_RightMargin;
’ps_TopMargin;
’ps_BottomMargin;
’ps_FontPointSize;
’ps_Leading;
Šps_Reserved3[8];
’ps_LeftEdge;
’ps_TopEdge;
’ps_Width;
’ps_Height;
Šps_Image;
Šps_Shading;
Šps_Dithering;
Šps_Reserved4[9];
Šps_Aspect;
Šps_ScalingType;
Šps_Reserved5;
Šps_Centering;
Šps_Reserved6[8];
};€DM_POSTSCRIPT 0€DM_PASSTHROUGH 1€PF_USLETTER 0€PF_USLEGAL 1€PF_A4 2€PF_CUSTOM 3€FONT_COURIER 0€FONT_TIMES 1€FONT_HELVETICA 2€FONT_HELV_NARROW 3€FONT_AVANTGARDE 4€FONT_BOOKMAN 5€FONT_NEWCENT 6€FONT_PALATINO 7€FONT_ZAPFCHANCERY 8€PITCH_NORMAL 0€PITCH_COMPRESSED 1€PITCH_EXPANDED 2€ORIENT_PORTRAIT 0€ORIENT_LANDSCAPE 1€TAB_4 0€TAB_8 1€TAB_QUART 2€TAB_HALF 3€TAB_INCH 4€IM_POSITIVE 0€IM_NEGATIVE 1€SHAD_BW 0€SHAD_GREYSCALE 1€SHAD_COLOR 2€DITH_DEFAULT 0€DITH_DOTTY 1€DITH_VERT 2€DITH_HORIZ 3€DITH_DIAG 4€ASP_HORIZ 0€ASP_VERT 1€ST_ASPECT_ASIS 0€ST_ASPECT_WIDE 1€ST_ASPECT_TALL 2€ST_ASPECT_BOTH 3€ST_FITS_WIDE 4€ST_FITS_TALL 5€ST_FITS_BOTH 6€CENT_NONE 0€CENT_HORIZ 1€CENT_VERT 2€CENT_BOTH 3‡